org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
# org.gradle.configuration-cache=true # For resopt
org.gradle.configureondemand=true
org.gradle.caching=true

kotlin.code.style=official

# Build BuildConfig as Bytecode
android.enableBuildConfigAsBytecode=true
# Generate compile-time only R class for app modules
android.enableAppCompileTimeRClass=true

android.suppressUnsupportedCompileSdk=37.0
